[package]
name = "bpf-rbac-lsm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
libbpf-rs = "0.26.2"
plain = "0.2.3"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
time = { version = "0.3.47", features = ["formatting", "local-offset", "macros"] }

[build-dependencies]
libbpf-cargo = "0.26.2"
